title: South Africam Financial Blockchain Consortium
email: info@safbc.co.za
description: The SAFBC aims to assimilate and demonstrate the transformative potential of blockchain technology for the South African financial industry
theme: jekyll-theme-tactile
twitter_username: SAFBC_ZA
