title: South African Financial Blockchain Consortium
email: info@safbc.co.za
logo: /images/SAFBC-Logo.PNG
description: Exploring the transformative potential of blockchain technology for the South African financial industry.
theme: jekyll-theme-minimal
twitter_username: SAFBC_ZA
plugins:
  - jekyll-gist